<
<template>
<div v-if="isLoading" class="loading-screen">
  <div class="loadingio-spinner-double-ring-nq4q5u6dq7r">
    <div class="ldio-x2uulkbinbj">
      <div></div>
      <div></div>
      <div><div></div></div>
      <div><div></div></div>
    </div>
  </div>
</div>

</template>


<script>
export default {
  props: {
    isLoading: {
      type: Boolean,
      required: false,
    },
  },
};
</script>
<style type="text/css">
.loading-screen {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  background-color: rgba(255, 255, 255, 0.8); /* สามารถปรับค่า opacity เพื่อทำให้พื้นหลังคลุม */
  z-index: 9000; /* ทำให้ loading อยู่ข้างหน้าทุกอย่าง */
}
@keyframes ldio-x2uulkbinbj {
  0% {
    transform: rotate(0);
  }
  100% {
    transform: rotate(360deg);
  }
}
.ldio-x2uulkbinbj div {
  box-sizing: border-box !important;
}
.ldio-x2uulkbinbj > div {
  position: absolute;
  width: 144px;
  height: 144px;
  top: 28px;
  left: 28px;
  border-radius: 50%;
  border: 16px solid #000;
  border-color: #013ca6 transparent #013ca6 transparent;
  animation: ldio-x2uulkbinbj 1s linear infinite;
}

.ldio-x2uulkbinbj > div:nth-child(2),
.ldio-x2uulkbinbj > div:nth-child(4) {
  width: 108px;
  height: 108px;
  top: 46px;
  left: 46px;
  animation: ldio-x2uulkbinbj 1s linear infinite reverse;
}
.ldio-x2uulkbinbj > div:nth-child(2) {
  border-color: transparent #a5a9ab transparent #a5a9ab;
}
.ldio-x2uulkbinbj > div:nth-child(3) {
  border-color: transparent;
}
.ldio-x2uulkbinbj > div:nth-child(3) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-x2uulkbinbj > div:nth-child(3) div:before,
.ldio-x2uulkbinbj > div:nth-child(3) div:after {
  content: "";
  display: block;
  position: absolute;
  width: 16px;
  height: 16px;
  top: -16px;
  left: 48px;
  background: #013ca6;
  border-radius: 50%;
  box-shadow: 0 128px 0 0 #013ca6;
}
.ldio-x2uulkbinbj > div:nth-child(3) div:after {
  left: -16px;
  top: 48px;
  box-shadow: 128px 0 0 0 #013ca6;
}

.ldio-x2uulkbinbj > div:nth-child(4) {
  border-color: transparent;
}
.ldio-x2uulkbinbj > div:nth-child(4) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-x2uulkbinbj > div:nth-child(4) div:before,
.ldio-x2uulkbinbj > div:nth-child(4) div:after {
  content: "";
  display: block;
  position: absolute;
  width: 16px;
  height: 16px;
  top: -16px;
  left: 30px;
  background: #a5a9ab;
  border-radius: 50%;
  box-shadow: 0 92px 0 0 #a5a9ab;
}
.ldio-x2uulkbinbj > div:nth-child(4) div:after {
  left: -16px;
  top: 30px;
  box-shadow: 92px 0 0 0 #a5a9ab;
}
.loadingio-spinner-double-ring-nq4q5u6dq7r {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-x2uulkbinbj {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-x2uulkbinbj div {
  box-sizing: content-box;
}
/* [ldio] generated by https://loading.io */
</style>
